# Numpy Arrays

### ndarray Attribute

In [1]:
import numpy as np

matrix = np.array([[ 1., 0., 0.],[ 0., 1., 2.]])
print("Dimensionalität:",matrix.ndim)
print("Form (rows,columns):",matrix.shape)
print("Total number of elements:",matrix.size)
print("Arrays Data Type:",matrix.dtype)
print("Byte Size of each element:",matrix.itemsize)

Dimensionalität: 2
Form (rows,columns): (2, 3)
Total number of elements: 6
Arrays Data Type: float64
Byte Size of each element: 8


### Matrizen mit Inhalt initialisieren

In [ ]:
zeros = np.zeros(shape=(3,2)) #3x2 Matrix komplett gefüllt mit 0
ones = np.ones(shape=(3,2)) #3x2 Matrix komplett gefüllt mit 1
random = np.random.rand(3,2) #3x2 Matrix komplett zufällig in [0,1] gefüllt

### Array Form verändern

In [3]:
matrix = np.array([[ 0,  1,  2,  3],[ 4,  5,  6,  7],[8, 9, 10, 11]])
print(matrix.shape) #(3,4)
print(matrix.reshape(1,12)) #2 Dimensionen festegelegt
print(matrix.reshape(-1,6)) #1 Dimension festgelegt, andere soll Numpy errechnen
print(matrix.reshape(7,3)) #Invalide Form - ValueError

(3, 4)
[[ 0  1  2  3  4  5  6  7  8  9 10 11]]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


ValueError: cannot reshape array of size 12 into shape (7,3)

### 1-Dim Array Dimension hinzufügen

In [4]:
vector = np.array([1, 2, 3])
print(vector.reshape(-1, 1))

[[1]
 [2]
 [3]]


### Indexierung eindimensionaler Arrays

In [5]:
vector = np.array([ 0,  1,  2,  3, 4,  5,  6,  7, 8, 9, 10, 11])
#Indexing: [von:bis:schrittgröße]
vector[1:3:1] #array([1, 2])
vector[2::2] #array([ 2,  4,  6,  8, 10])
vector[::3] #array([0, 3, 6, 9])

array([0, 3, 6, 9])

### Indexierung mehrdimensionaler Arrays (1/2)

In [6]:
matrix = np.array([[ 0,  1,  2],[10, 11, 12],[20, 21, 22]])
#array([[ 0,  1,  2],
#       [10, 11, 12],
#       [20, 21, 22]])
matrix[1:2,1:2] #array([[11]])

array([[11]])

### Indexierung mehrdimensionaler Arrays (2/2)

In [7]:
matrix = np.array([[ 0,  1,  2, 3],[10, 11, 12, 13],[20, 21, 22, 23],[30, 31, 32, 33]])
#array([[ 0,  1,  2,  3],
#       [10, 11, 12, 13],
#       [20, 21, 22, 23],
#       [30, 31, 32, 33]])
matrix[1:3,2:]

array([[12, 13],
       [22, 23]])

### Arrays flatten

In [8]:
matrix = np.array([[ 0,  1],[10, 11],[20, 21]])
print(matrix.shape) #(3, 2)
matrix = matrix.ravel() #array([ 0,  1, 10, 11, 20, 21])
print(matrix.shape) #(6,)

(3, 2)
(6,)


### Flache Arrays als iterator

In [9]:
matrix = np.array([[0,  1],[10, 11],[20, 21]])
for element in matrix.flat:
    print(element)

0
1
10
11
20
21


### Arrays squeezen

In [10]:
vector = np.array([0,1,2,3])
vector.resize(4,1,1,1)
print(vector) #[[[[0]]] [[[1]]] [[[2]]] [[[3]]]]
print(vector.squeeze()) #[0 1 2 3]

[[[[0]]]


 [[[1]]]


 [[[2]]]


 [[[3]]]]
[0 1 2 3]


### Mit Arrays rechnen

In [11]:
v1 = np.array([0,1,2,3])
v2 = np.array([4,5,6,7])

print(v1+v2) #[ 4  6  8 10]
print(v1-v2) #[-4 -4 -4 -4]
print(v1*v2) #[ 0  5 12 21]
print(v1/v2) #[0. 0.2 0.33 0.428]
print(np.dot(v1,v2)) #38

[ 4  6  8 10]
[-4 -4 -4 -4]
[ 0  5 12 21]
[0.         0.2        0.33333333 0.42857143]
38
